config/routes.rb
Emulatorization::Application.routes.draw do
  
  devise_for :users

  match "api" => "api#index"
  match "service_status" => "service_status#index"

  resources :emulator_projects do
    resources :simulator_specifications do
      resources :inputs
    end
    resources :input_screenings
    resources :designs
    resources :runs
    resources :emulators
    resources :validations
  end

  resources :sensitivity_projects do
    resources :simulator_specifications
    resources :analyses
  end

  resources :validation_projects
  
  root :to => "home#index"
  

end

app/models/design.rb
class Design
  include Mongoid::Document
  include Remote::Remotable
  
  belongs_to :simulator_specification
  belongs_to :designable, polymorphic: true
  
  has_many :design_values
  has_one :run
  
  field :size, type: Integer
  field :sampling_method, type: String, default: "lhs"
  
  validates_inclusion_of :sampling_method, in: ["lhs"]

  def calculate_defaults
    self.size = self.designable.simulator_specification.inputs.size * 30
  end
  
  def to_hash
    { size: self.size,
      map: design_values.collect {|value| value.to_hash } }
  end
  
  def to_matlab
    "struct(" + design_values.map {|value| "'#{value.input.name}',#{value.points}" }.join(",") + ")"
    # matrix = design_values.collect {|value| value.points }.transpose
    # annoying as join works on inner arrays too
    # "[#{matrix.collect {|points| points.join(',') }.join(';')}]"
  end
  
  def to_r
    "data.frame(#{design_values.collect {|value| "#{value.input.name}=c(#{value.points.join(',')})"}.join(',')})"
  end
  
  def generate
    # request hash
    {
      type: 'DesignRequest',
      size: size,
      inputs: self.simulator_specification.inputs.reject {|input| input.fixed? }.collect {|input| input.to_hash }
    }
  end
  
  def handle(response)
    # get specifications
    inputs = self.simulator_specification.inputs
    
    # parse design
    response['design']['map'].each do |set|
      input = inputs.where(:name => set['inputIdentifier']).first
      self.design_values.create(input: input, points: set['points'])
    end
  end
end

app/controllers/designs_controller.rb
class DesignsController < Remote::RemotableController
  layout "emulator_project"

  def show_respond_to(format)
    format.json {
      if params[:input_id]
        value = @design.design_values.where(input_id: params[:input_id]).first
        render json: value.to_hash
      else
        render json: @design.to_hash
      end
    }
  end
end

app/views/designs/_buttons.html.erb
<div class="btn-group">
  <% if false and parent.has_run? %>
    <%= link_to "View Run", emulator_project_runs_path(parent), class: "btn" %>
  <% else %>
    <%= simple_form_for [parent, Run.new], html: { class: "form-inline" } do |f| %>
      <%= f.button :submit %>
      <%= f.input :simulator_specification_id, as: :hidden, input_html: { value: parent.simulator_specification.id } %>
      <%= f.input :design_id, as: :hidden, input_html: { value: object.id } %>
    <% end %>
  <% end %>
</div>

app/views/designs/_display.html.erb
<script>
var plot;

$(function() {
  // create histogram
  plot = createHistogram('histogram-container', <%= @design.design_values.first.to_hash.to_json.html_safe %>, 'points', $('#bins').val());
  
  // listener for form
  $('.inline-controls form').on('submit', function() {
    return false;
  });

  $('.inline-controls select,input').on('change', function(e) {
    remoteUpdateHistogram(plot, '<%= emulator_project_design_path(@project, @design) %>' + '.json', { input_id: $('#input').val() }, 'points', $('#bins').val());
    return false;
  }); 
});
</script>

<%= simple_form_for [@project, Run.new] do |f| %>
  <%# f.input :simulator_specification_id, as: :hidden, input_html: { value: @project.simulator_specification.id } %>
  <%# f.input :design_id, as: :hidden, input_html: { value: @project.design.id } %>
  <%# f.button :submit %>
<% end %>

<%= render partial: "shared/toolbar", locals: { text: "This #{@design.sampling_method.upcase} design has #{pluralize(@design.size, 'point')} for #{pluralize(@design.design_values.size, 'input')}.", parent: @project, object: @design, export_options: ["matlab", "r", "json"] } %>

<div class="row">
  <div class="span12">
    <div class="tabbable">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#histogram" data-toggle="tab">Histogram</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="histogram">
          <div class="inline-controls">
            <form class="well form-inline">
              <label for="input">Input</label>
              <select id="input" class="input-large">
                <% @design.design_values.each do |value| %>
                <% input = value.input %>
                <%= content_tag(:option, value: input.id) { input.name } %>
                <% end %>
              </select>
              <label for="bins">Bins</label>
              <input id="bins" type="number" value="10" step="5" class="input-small" />
            </form>
          </div>
          <div id="histogram-container" class="plot"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/designs/_form.html.erb
<div class="row">
  <div class="span7">
    <%= simple_form_for [@project, @design], html: { class: 'form-horizontal' } do |f| %>
      <%= f.error_notification %>

      <%= f.input :simulator_specification_id, as: :hidden, input_html: { value: @project.simulator_specification.id } %>
      <%= f.input :size %>
      <%= f.input :sampling_method, include_blank: false, collection: [["Latin hypercube", "lhs"]] %>
      
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/designs/_header.html.erb
<%= page_header "Design", t("designs.strap") %>

app/views/designs/edit.html.erb
<%= render "form" %>

app/views/designs/new.html.erb
<%= render "form" %>

app/views/designs/show.html.erb
<%= javascript_include_tag "export" %>
<%= javascript_include_tag "highcharts/highcharts" %>
<%= javascript_include_tag "charts" %>

<%= remote_display(@design, @project) %>