config/routes.rb
Emulatorization::Application.routes.draw do
  
  devise_for :users

  match "api" => "api#index"
  match "service_status" => "service_status#index"

  resources :emulator_projects do
    resources :simulator_specifications do
      resources :inputs
    end
    resources :input_screenings
    resources :designs
    resources :runs
    resources :emulators
    resources :validations
  end

  resources :sensitivity_projects do
    resources :simulator_specifications
    resources :analyses
  end

  resources :validation_projects
  
  root :to => "home#index"
  

end

app/models/input_screening.rb
class InputScreening
  include Mongoid::Document
  include Remote::Remotable
  
  belongs_to :emulator_project
  has_many :screening_values
  
  field :num_trajectories, type: Integer, default: 5
  field :discretisation_level, type: Integer, default: 10
  field :delta_p, type: Integer, default: 1
  
  def to_hash
    self.screening_values.collect {|value| value.to_hash }
  end
  
  def generate
    # get project and spec
    project = self.emulator_project
    spec = project.simulator_specification
    
    # request hash
    { type: 'ScreeningRequest',
      serviceURL: spec.service_url,
      processIdentifier: spec.process_name,
      inputs: spec.inputs.collect {|input| input.to_hash },
      outputs: spec.outputs.collect {|output| output.to_hash },
      numTrajectories: self.num_trajectories,
      discretisationLevel: self.discretisation_level,
      deltaP: self.delta_p }
  end
  
  def handle(response)
    # get input and output specifications
    project = self.emulator_project
    spec = project.simulator_specification
    inputs = spec.inputs
    outputs = spec.outputs
    
    # parse run
    response['results'].each do |set|
      output = outputs.where(:name => set['outputIdentifier']).first
      screening_value = self.screening_values.create(output: output)
      set['inputResults'].each do |input_set|
        input = inputs.where(:name => input_set['inputIdentifier']).first
        screening_value.screening_input_values.create(input: input, mean_ee: input_set['meanEE'], mean_star_ee: input_set['meanStarEE'], std_ee: input_set['stdEE'], ee: input_set['ee'])
      end
    end
  end

  def remove_input(name)
    screening_values.each do |value|
      screening_value.screening_input_values.each do |input_value|
        if input_value.input.name == name
          input_value.destroy
        end
      end
    end
  end
end

app/controllers/input_screenings_controller.rb
class InputScreeningsController < Remote::RemotableController
  layout "emulator_project"
  
  def show_respond_to(format)
    object = if params[:output_id]
      @input_screening.screening_values.where(output_id: params[:output_id]).first
    else
      @input_screening
    end
    format.json {
      render json: object.to_hash
    }
    format.matlab {
      render text: object.to_matlab
    }
    format.r {
      render text: object.to_r
    }
  end
end

app/views/input_screenings/_display.html.erb
<script>
var plot;

$(function() {
  // create chart
  plot = createScreeningPlot('plot-container', <%= @input_screening.screening_values.first.to_hash.to_json.html_safe %>);
  
  // listener for form
  $('.inline-controls form').on('submit', function() {
    return false;
  });

  $('.inline-controls select,input').on('change', function() {
    remoteUpdateScreeningPlot(plot, '<%= emulator_project_input_screening_path(@project, @input_screening) %>' + '.json', { output_id: $('#output').val() });
    return false;
  });
    
});
</script>

<%= render partial: "shared/toolbar", locals: { text: "Took #{distance_of_time_in_words Time.parse(@input_screening.proc_start_time.to_s), Time.parse(@input_screening.proc_end_time.to_s), true} to perform input screening with #{@input_screening.num_trajectories} trajectories, a discretisation level of #{@input_screening.discretisation_level} and delta P at #{@input_screening.delta_p}.", parent: @project, object: @input_screening, export_options: ["matlab", "r", "json"], export_filter: @input_screening.screening_values.collect {|value| value.output }.uniq } %>

<div id="popup" class="right">
</div>

<div class="row">
  <div class="span12">
    <div class="tabbable">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#plot" data-toggle="tab">Plot</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="plot">
          <div class="inline-controls">
            <form class="well form-inline">
              <label for="output">Output</label>
              <select id="output" class="input-medium">
                <% @input_screening.screening_values.collect {|value| value.output }.uniq.each do |output| %>
                <%= content_tag(:option, value: output.id) { output.name } %>
                <% end %>
              </select>
            </form>
          </div>
          <div id="plot-container" class="plot"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<textarea class="template hide" data-simulator-specification-url="<%= url_for [@project, @project.simulator_specification] %>">
  <div class="top">
    <h3>{{name}}</h3>
    <span class="close">x</span>
  </div>
  <div class="content">
    <div>meanStarEE: {{meanStarEE}}, stdEE: {{stdEE}}</div>
    <div>minimum: {{minimumValue}}, maximum: {{maximumValue}}</div>
    <form class="form-inline" method="put" action="{{url}}" data-remote="true">
      <input type="hidden" name="input[minimum_value]" value="" />
      <input type="hidden" name="input[maximum_value]" value="" />
      <input type="text" class="input-small" placeholder="Value" name="input[fixed_value]" value="{{fixedValue}}">
      <button type="submit" class="btn">Fix input</button>
    </form>
  </div>
</textarea>

app/views/input_screenings/_form.html.erb
<%= simple_form_for [@project, @input_screening], html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  
  <%= f.input :num_trajectories %>
  <%= f.input :discretisation_level %>
  <%= f.input :delta_p %>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/input_screenings/_header.html.erb
<%= page_header "Input screening", t("input_screenings.strap") %>

app/views/input_screenings/edit.html.erb
<div class="row">
  <div class="span7">
    <%= render "form" %>
  </div>
</div>

app/views/input_screenings/new.html.erb
<div class="row">
  <div class="span7">
    <%= render "form" %>
  </div>
</div>

app/views/input_screenings/show.html.erb
<%= javascript_include_tag "mustache" %>
<%= javascript_include_tag "highcharts/highcharts" %>
<%= javascript_include_tag "charts" %>

<%= remote_display(@input_screening, @project) %>