config/routes.rb
Emulatorization::Application.routes.draw do
  
  devise_for :users

  match "api" => "api#index"
  match "service_status" => "service_status#index"

  resources :emulator_projects do
    resources :simulator_specifications do
      resources :inputs
    end
    resources :input_screenings
    resources :designs
    resources :runs
    resources :emulators
    resources :validations
  end

  resources :sensitivity_projects do
    resources :simulator_specifications
    resources :analyses
  end

  resources :validation_projects
  
  root :to => "home#index"
  

end

app/models/run.rb
class Run
  include Mongoid::Document
  include Remote::Remotable
  
  belongs_to :simulator_specification
  belongs_to :runnable, polymorphic: true
  belongs_to :design
  
  has_many :run_values
  
  field :size, type: Integer
  
  def to_hash
    self.run_values.collect {|value| value.to_hash }
  end
  
  def to_matlab
    "struct(" + run_values.map {|value| "'#{value.output.name}',#{value.points}" }.join(",") + ")"
    # matrix = run_values.collect {|value| value.points }.transpose
    # annoying as join works on inner arrays too
    # "[#{matrix.collect {|points| points.join(',') }.join(';')}]"
  end
  
  def to_r
    "data.frame(#{run_values.collect {|value| "#{value.output.name}=c(#{value.points.join(',')})"}.join(',')})"
  end
  
  def generate
    # get spec
    spec = self.simulator_specification
    
    # request hash
    { type: 'EvaluateProcessRequest',
      serviceURL: spec.service_url,
      processIdentifier: spec.process_name,
      inputs: spec.inputs.collect {|input| input.to_hash },
      outputs: spec.outputs.collect {|output| output.to_hash },
      design: self.design.to_hash }
  end
  
  def handle(response)
    # get project and output specifications
    outputs = self.simulator_specification.outputs
    
    # parse run
    response['evaluationResult'].each do |set|
      output = outputs.where(:name => set['outputIdentifier']).first
      self.run_values.create(output: output, points: set['results'])
    end
    
    # set size
    self.size = self.design.size
  end
end

app/controllers/runs_controller.rb
class RunsController < Remote::RemotableController
  layout "emulator_project"
  
  def show_respond_to(format)
    format.json {
      if params[:output_id]
        value = @run.run_values.where(output_id: params[:output_id]).first
        render json: value.to_hash
      else
        render json: @run.to_hash
      end
    }
  end
end

app/views/runs/_display.html.erb
<script>
var plot;

$(function() {
  // create histogram
  plot = createHistogram('histogram-container', <%= @run.run_values.first.to_hash.to_json.html_safe %>, 'results', $('#bins').val());
  
  // listener for form
  $('.inline-controls form').on('submit', function() {
    return false;
  });

  $('.inline-controls select,input').on('change', function() {
    remoteUpdateHistogram(plot, '<%= emulator_project_run_path(@project, @run) %>' + '.json', { output_id: $('#output').val() }, 'results', $('#bins').val());
    return false;
  }); 
});
</script>

<%= render partial: "shared/toolbar", locals: { text: "Took #{distance_of_time_in_words Time.parse(@run.proc_start_time.to_s), Time.parse(@run.proc_end_time.to_s), true} to perform #{pluralize @run.size, "run"}.", parent: @project, object: @run, export_options: ["matlab", "r", "json"] } %>

<%# "#{@run.proc_start_time} to #{@run.proc_end_time}" %>

<div class="row">
  <div class="span12">
    <div class="tabbable">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#histogram" data-toggle="tab">Histogram</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="histogram">
          <div class="inline-controls">
            <form class="well form-inline">
              <label for="output">Output</label>
              <select id="output" class="output-medium">
                <% @run.run_values.each do |value| %>
                <% output = value.output %>
                <%= content_tag(:option, value: output.id) { output.name } %>
                <% end %>
              </select>
              <label for="bins">Bins</label>
              <input id="bins" type="number" value="10" step="5" class="input-small" />
            </form>
          </div>
          <div id="histogram-container" class="plot"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/runs/_form.html.erb
<div class="row">
  <div class="span7">
    <%= simple_form_for [@project, @run], html: { class: 'form-horizontal' } do |f| %>
      <%= f.input :simulator_specification_id, as: :hidden, input_html: { value: @project.simulator_specification.id } %>
      <%= f.input :design_id, as: :hidden, input_html: { value: @project.design.id } %>
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/runs/_header.html.erb
<%= page_header "Run", t("runs.strap") %>

app/views/runs/edit.html.erb
<%= render "form" %>

app/views/runs/new.html.erb
<%= render "form" %>

app/views/runs/show.html.erb
<%= javascript_include_tag "export" %>
<%= javascript_include_tag "highcharts/highcharts" %>
<%= javascript_include_tag "charts" %>

<%= remote_display(@run, @project) %>